import { createApp, h } from 'vue'
import {RouterView} from 'vue-router'
import {router} from './router.js'
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import {ElConfigProvider} from 'element-plus/es/components/config-provider/index'
import {ElDropdown,ElDropdownMenu,ElDropdownItem} from 'element-plus/es/components/dropdown/index'
import 'element-plus/es/components/dropdown/style/css'
import {ElButton} from 'element-plus/es/components/button/index'
import {ElSwitch} from 'element-plus/es/components/switch/index'
import 'element-plus/es/components/switch/style/css'
import {ElInput} from 'element-plus/es/components/input/index'
import {ElInputNumber} from 'element-plus/es/components/input-number/index'
import {ElSelect} from 'element-plus/es/components/select/index'
import {ElOption} from 'element-plus/es/components/select/index'
import {ElCheckbox} from 'element-plus/es/components/checkbox/index'
import {ElRadioGroup} from 'element-plus/es/components/radio/index'
import {ElRadioButton} from 'element-plus/es/components/radio/index'
import {ElForm} from 'element-plus/es/components/form/index'
import {ElFormItem} from 'element-plus/es/components/form/index'
import {ElDrawer} from 'element-plus/es/components/drawer/index'
import 'element-plus/es/components/drawer/style/css'
import {ElDialog} from 'element-plus/es/components/dialog/index'
import {ElTabs} from 'element-plus/es/components/tabs/index'
import {ElTabPane} from 'element-plus/es/components/tabs/index'
import {ElTable} from 'element-plus/es/components/table/index'
import {ElTableColumn} from 'element-plus/es/components/table/index'
import {ElTag} from 'element-plus/es/components/tag/index'
import {ElAlert} from 'element-plus/es/components/alert/index'
import {ElAvatar} from 'element-plus/es/components/avatar/index'
import {ElCollapse} from 'element-plus/es/components/collapse/index'
import {ElCollapseItem} from 'element-plus/es/components/collapse/index'
import {ElEmpty} from 'element-plus/es/components/empty/index'
import {ElTooltip} from 'element-plus/es/components/tooltip/index'
import {ElIcon} from 'element-plus/es/components/icon/index'
import 'element-plus/es/components/base/style/css'
import 'element-plus/es/components/button/style/css'
import 'element-plus/es/components/input/style/css'
import 'element-plus/es/components/input-number/style/css'
import 'element-plus/es/components/select/style/css'
import 'element-plus/es/components/option/style/css'
import 'element-plus/es/components/checkbox/style/css'
import 'element-plus/es/components/radio-group/style/css'
import 'element-plus/es/components/radio-button/style/css'
import 'element-plus/es/components/form/style/css'
import 'element-plus/es/components/form-item/style/css'
import 'element-plus/es/components/dialog/style/css'
import 'element-plus/es/components/tabs/style/css'
import 'element-plus/es/components/tab-pane/style/css'
import 'element-plus/es/components/table/style/css'
import 'element-plus/es/components/table-column/style/css'
import 'element-plus/es/components/tag/style/css'
import 'element-plus/es/components/alert/style/css'
import 'element-plus/es/components/avatar/style/css'
import 'element-plus/es/components/collapse/style/css'
import 'element-plus/es/components/collapse-item/style/css'
import 'element-plus/es/components/empty/style/css'
import 'element-plus/es/components/tooltip/style/css'
import 'element-plus/es/components/icon/style/css'
import 'element-plus/es/components/config-provider/style/css'
import 'element-plus/theme-chalk/dark/css-vars.css'
import './style.css'
import './config-panels.css'
const app=createApp({render:()=>h(ElConfigProvider,{locale:zhCn,emptyValues:[null,undefined]},()=>h(RouterView))})
for(const component of [ElDropdown,ElDropdownMenu,ElDropdownItem,ElSwitch,ElButton,ElInput,ElInputNumber,ElSelect,ElOption,ElCheckbox,ElRadioGroup,ElRadioButton,ElForm,ElFormItem,ElDialog,ElDrawer,ElTabs,ElTabPane,ElTable,ElTableColumn,ElTag,ElAlert,ElAvatar,ElCollapse,ElCollapseItem,ElEmpty,ElTooltip,ElIcon])app.component(component.name,component)
app.use(router)
router.isReady().then(()=>app.mount('#app'))

import './element-theme.css'
